routes/web.php
<?php


use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::resource("commandes", CommandeController::class);

Route::middleware(['guest'])->group(function () {
    Route::get('/', [HomeController::class, "index"])->name("index");
    Route::post('/add-panier', [HomeController::class, "addPanier"])->name("add-panier");
    Route::get('/show-panier', [HomeController::class, "showPanier"])->name("show-panier");
    Route::get('/clear-panier', [HomeController::class, "clearPanier"])->name("clear-panier-item");
    Route::post('/remove-panier-item', [HomeController::class, "removePanier"])->name("remove-panier-item");
});

Route::middleware(['auth'])->group(function () {
    
    Route::view('profile', 'profile')->name('profile');
    Route::view('dashboard', 'dashboard')->name('dashboard');
    Route::get("/categories/search", [CategorieController::class, "search"])->name("categories.search");
    Route::get("/produits/search", [ProduitController::class, "search"])->name("produits.search");
    
    Route::resource("categories", CategorieController::class);
    Route::resource("produits", ProduitController::class);
    

});






// Route::get('/', [HomeController::class, "index"])->name("index");




// Route::get('/produits', [ProduitController::class, 'filter'])->name('produits.filter');
// Route::get('/produits/filter', [ProduitController::class, 'index'])->name('produits.index');
require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/categorie.blade.php
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Categories') }}
        </h2>
    </x-slot>

    <div class="container m-auto">
        {{-- Search and Ajouter --}}
        <h1 class="mt-5 mb-3">Liste des categories</h1>
        <form action="{{ route('categories.search') }}" method="get">
            <div class="input-group mb-3">
                <input type="text" class="form-control" name="designation">
                <button class="input-group-text" type="submit">
                    <img src="{{ asset('/search.png') }}">
                </button>
                <div id="ajouter"><a class="ms-2 btn btn-primary" href="{{ route('categories.create') }}">Ajouter
                        categorie</a></div>
            </div>
        </form>

        {{-- reset --}}
        <a href="{{ route('categories.index') }}">list des categories</a>

        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">

        {{-- Viewer --}}
        <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <thead  class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <th>Id</th>
                <th>Designation</th>
                <th>Description</th>
                <th colspan="3">Actions</th>
            </thead>
            <tbody>
                @foreach ($categories as $cat)
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row"
                            class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ $cat->id }}
                        </th>
                        <td class="px-6 py-4">
                            {{ $cat->designation }}
                        </td>
                        <td class="px-6 py-4">
                            {{ $cat->description }}
                        </td>
                        <td class="px-6 py-4 text-right flex gap-2">
                            <a href="{{ route('categories.show', ['category' => $cat->id]) }}">
                                <img src="{{ asset('/details.png') }}">
                            </a>
                            <a class="btn btn-success" href="{{ route('categories.edit', ['category' => $cat->id]) }}">
                                <img src="{{ asset('/change.png') }}">
                            </a>
                            <form action="{{ route('categories.destroy', ['category' => $cat->id]) }}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" type="submit"
                                    onclick="return confirm('voulez-vous supprimer cette categorie?')">
                                    <img src="{{ asset('/delete.png') }}">
                                </button>

                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</x-app-layout>

resources/views/commande.blade.php
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Commandes') }}
        </h2>
    </x-slot>

    <div class="container">
        <p>Filter By :</p>
        <form action="{{ route('commandes.index') }}">
            <div class="row">
                <div class="col-3">
                    <label class="form-label" for="client">client</label>
                    <input class="form-input" type="text" name="client">
                </div>
                <div class="col-3">
                    <label class="form-label" for="etat">etat_id</label>
                    <input class="form-input" type="text" name="etat">
                </div>
                <div class="col-3">
                    <label class="form-label" for="etat">date min</label>
                    <input class="form-input" type="date" name="date_min">
                </div>
                <div class="col-3">
                    <label class="form-label" for="etat">date max</label>
                    <input class="form-input" type="date" name="date_max">
                </div>
            </div>
            <input type="submit" value="Filter">
        </form>

        <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <th>Id</th>
                <th>client name</th>
                <th>etat</th>
                <th colspan="3">Actions</th>
            </thead>
            <tbody>
                @foreach ($commandes as $commande)
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row"
                            class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ $commande->id }}
                        </th>
                        <td class="px-6 py-4">
                            {{ $commande->client->nom }}
                        </td>
                        <td class="px-6 py-4">
                            {{ $commande->etat->intitule }}
                        </td>
                        <td class="px-6 py-4 text-right flex gap-2">
                            <a href="#">
                                <img src="{{ asset('/details.png') }}">
                            </a>
                            <a class="btn btn-success" href="#">
                                <img src="{{ asset('/change.png') }}">
                            </a>
                            <form action="" method="POST">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger" type="submit"
                                    onclick="return confirm('voulez-vous supprimer cette categorie?')">
                                    <img src="{{ asset('/delete.png') }}">
                                </button>

                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</x-app-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Dashboard') }}
        </h2>
        
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    {{ __("You're logged in!") }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/produit.blade.php
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Produits') }}
        </h2>
    </x-slot>

    <div class="container m-auto">
  
        <div id="ajouter">
            <a class="ms-2 btn btn-primary" href="{{ route('produits.create') }}">Ajouter Produit</a>
        </div>

        {{-- reset --}}
        <a href="{{ route('produits.index') }}">list des produits</a>


        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                <caption
                    class="p-5 text-lg font-semibold text-left rtl:text-right text-gray-900 bg-white dark:text-white dark:bg-gray-800">
                    Our products
                    <p class="mt-1 text-sm font-normal text-gray-500 dark:text-gray-400">Browse a list of Flowbite
                        products designed to help you work and play, stay organized, get answers, keep in touch, grow
                        your business, and more.</p>
                    <form action="{{ route('produits.index') }}" method="get">
                        <div class="input-group mb-3">
                            <label for="designation">designation</label>
                            <input type="text" class="form-control" name="designation"
                                value="{{ old('designation') }}">
                            <label for="min_price">min price</label>
                            <input class="form-control" type="text" name="min_price" value="{{ old('min_price') }}">
                            <label for="min_price">max price</label>
                            <input class="form-control" type="text" name="max_price" value="{{ old('max_price') }}">
                            <input type="submit" value="submit">
                    </form>
                </caption>
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Designation
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Prix U
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Quantité
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Categorie Id
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($produits as $prod)
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                            <th scope="row"
                                class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{ $prod->designation }}
                            </th>
                            <td class="px-6 py-4">
                                {{ $prod->prix_u }}
                            </td>
                            <td class="px-6 py-4">
                                ${{ $prod->quantite_stock }}
                            </td>
                            <td class="px-6 py-4">
                                {{ $prod->categorie_id }}
                            </td>
                            <td class="px-6 py-4 text-right flex gap-2">
                                <a href="{{ route('produits.show', ['produit' => $prod->id]) }}">
                                    <img src="{{ asset('/details.png') }}">
                                </a>

                                <a class="btn btn-success"
                                    href="{{ route('produits.edit', ['produit' => $prod->id]) }}">
                                    <img src="{{ asset('/change.png') }}">
                                </a>

                                <form action="{{ route('produits.destroy', ['produit' => $prod->id]) }}"
                                    method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-danger" type="submit"
                                        onclick="return confirm('voulez-vous supprimer ce produit?')">
                                        <img src="{{ asset('/delete.png') }}">
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>


        <div>
            <p> results {{ $produits->count() }} of {{ $produits->total() }}</p>
            <div></div>
        </div>
        {{ $produits->links() }}
    </div>

</x-app-layout>

resources/views/profile.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Profile') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <livewire:profile.update-profile-information-form />
                </div>
            </div>

            <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <livewire:profile.update-password-form />
                </div>
            </div>

            <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                <div class="max-w-xl">
                    <livewire:profile.delete-user-form />
                </div>
            </div>
        </div>
    </div>
</x-app-layout>