routes/web.php
<?php


use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::resource("commandes", CommandeController::class);

Route::middleware(['guest'])->group(function () {
    Route::get('/', [HomeController::class, "index"])->name("index");
    Route::post('/add-panier', [HomeController::class, "addPanier"])->name("add-panier");
    Route::get('/show-panier', [HomeController::class, "showPanier"])->name("show-panier");
    Route::get('/clear-panier', [HomeController::class, "clearPanier"])->name("clear-panier-item");
    Route::post('/remove-panier-item', [HomeController::class, "removePanier"])->name("remove-panier-item");
});

Route::middleware(['auth'])->group(function () {
    
    Route::view('profile', 'profile')->name('profile');
    Route::view('dashboard', 'dashboard')->name('dashboard');
    Route::get("/categories/search", [CategorieController::class, "search"])->name("categories.search");
    Route::get("/produits/search", [ProduitController::class, "search"])->name("produits.search");
    
    Route::resource("categories", CategorieController::class);
    Route::resource("produits", ProduitController::class);
    

});






// Route::get('/', [HomeController::class, "index"])->name("index");




// Route::get('/produits', [ProduitController::class, 'filter'])->name('produits.filter');
// Route::get('/produits/filter', [ProduitController::class, 'index'])->name('produits.index');
require __DIR__ . '/auth.php';

app/Models/Commande.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Commande extends Model
{
    use HasFactory;
   protected $table = "commande";

    protected $fillable=[
        "client_id",
        "etat_id"
    ];
    public function client(){
        return $this->belongsTo(Client::class,"client_id");
    }
    public function produit(){
        return $this->belongsTo(Produit::class);
     }
    public function etat(){
        return $this->hasOne(Etat::class,"id");
    }

    // protected function 
}

app/Http/Controllers/CommandeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Etat;
use App\Models\Client;
use App\Models\Commande;
use Illuminate\Http\Request;
use App\Models\LigneCommande;
use App\Http\Controllers\Controller;

class CommandeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
       $commandes=Commande::all();
       
        return view("commande",compact('commandes'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view("commandes.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $client = [
            "nom"=>$request->nom,
            "prenom"=>$request->prenom,
            "ville"=>$request->ville,
            "adresse"=>$request->adresse,
            "tele"=>$request->tele,
        ];
        $produits = session()->get("user.produits");

        $client = Client::create($client);
        $etat = Etat::create(["intitule"=>"EN ATTENT DE CONFIRMATION","description"=>"EN ATTENT DE CONFIRMATION"]);
        $command = Commande::create(["client_id"=>$client->id,"etat_id"=>$etat->id]);
        foreach($produits as $prod){
            LigneCommande::create([
                "commande_id"=>$command->id,
                "produit_id"=>$prod["id"],
                "qte"=>$prod["qnt"],
                "prix"=>$prod["prix_u"]

            ]);
        }

        return "Your Commande is Fully Noted";


    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/commandes/create.blade.php
@extends('layouts.admin')
@section('title', 'Create Commande')
@section('content')
    <h1>Creer une nouvelle Client</h1>
    <form action="{{ route('commandes.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="input-group-text">
            <label for="designation">nom:</label>
            <input name="nom" class="form-control mt-0 ms-2" type="text"
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="prenom">prenom:</label>
            <input name="prenom" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="description">ville:</label>
            <input name="ville" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>


        <div class="input-group-text mt-2">
            <label for="description">adress:</label>
            <input name="adresse" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="description">tele:</label>
            <input name="tele" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <div class="mt-3">
            <input type="submit" class="btn btn-primary" value="Command">
        </div>

    </form>
    <div>
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $er)
                    <li>{{ $er }}</li>
                @endforeach
            </ul>
        @endif
    </div>
@endsection