routes/web.php
<?php


use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProduitController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::resource("commandes", CommandeController::class);

Route::middleware(['guest'])->group(function () {
    Route::get('/', [HomeController::class, "index"])->name("index");
    Route::post('/add-panier', [HomeController::class, "addPanier"])->name("add-panier");
    Route::get('/show-panier', [HomeController::class, "showPanier"])->name("show-panier");
    Route::get('/clear-panier', [HomeController::class, "clearPanier"])->name("clear-panier-item");
    Route::post('/remove-panier-item', [HomeController::class, "removePanier"])->name("remove-panier-item");
});

Route::middleware(['auth'])->group(function () {
    
    Route::view('profile', 'profile')->name('profile');
    Route::view('dashboard', 'dashboard')->name('dashboard');
    Route::get("/categories/search", [CategorieController::class, "search"])->name("categories.search");
    Route::get("/produits/search", [ProduitController::class, "search"])->name("produits.search");
    
    Route::resource("categories", CategorieController::class);
    Route::resource("produits", ProduitController::class);
    

});






// Route::get('/', [HomeController::class, "index"])->name("index");




// Route::get('/produits', [ProduitController::class, 'filter'])->name('produits.filter');
// Route::get('/produits/filter', [ProduitController::class, 'index'])->name('produits.index');
require __DIR__ . '/auth.php';

app/Models/Produit.php
<?php

namespace App\Models;

use App\Models\Categorie;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Produit extends Model
{
    use HasFactory;

    protected $fillable =[
        'designation',
        'prix_u',
        'quantite_stock',
        'categorie_id',
        'photo',
    ];
    public function categorie(){
        return  $this->belongsTo(Categorie::class);
    }
    // public function scopeFilterByPrice($query, $minPrice, $maxPrice)
    // {
    //     if ($minPrice) {
    //         $query->where('prix_u', '>=', $minPrice);
    //     }

    //     if ($maxPrice) {
    //         $query->where('prix_u', '<=', $maxPrice);
    //     }

    //     return $query;
    // }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produit;
use App\Models\Categorie;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\File;

class ProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $produits = Produit::paginate(10);
        $query_builder = Produit::query();

        $designiation = $request->input("designation");
        $min_price = $request->input("min_price");
        $max_price = $request->input("max_price");

        if ($designiation) {
            $query_builder->where("designation", "like", "%" . $designiation . "%");
            $produits = $query_builder->paginate();
        }

        if ($min_price and $max_price) {
            $query_builder->whereBetween("prix_u", [$min_price, $max_price]);
            $produits = $query_builder->paginate();
        }






        return view("produit", compact('produits'));
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $cats = Categorie::all();
        return view('produits.create', compact('cats'));
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'designation' => 'required|unique:categories,designation',
            'prix_u' => 'required|numeric',
            'quantite_stock' => 'required|numeric',
            'categorie_id' => 'required',
            'photo' => 'image|mimes:jpeg,jpg,png,gif,svg|max:512000'

        ]);

        if ($request->hasFile('photo')) {
            $imagePath = $request->file('photo')->store('products/images', 'public');
            $validatedData['photo'] = $imagePath;
        }
        Produit::create($validatedData);
        return  redirect()->route('produits.index');
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
        $prod = Produit::find($id);
        return view('produits.show')->with("prod", $prod);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $prod = Produit::find($id);
        $cats = Categorie::all();
        $data = ["prod" => $prod, "cats" => $cats];

        return view('produits.edit', compact('data'));
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'designation' => 'required|unique:categories,designation',
            'prix_u' => 'required|numeric',
            'quantite_stock' => 'required|numeric|decimal:0',
            'categorie_id' => 'required',
            /*
            'photo' => [
                'required',
                File::image()
                    ->min(1024)
                    ->max(12 * 1024)
                    ->dimensions(Rule::dimensions()->maxWidth(1000)->maxHeight(500))
                    
            ]
            */


        ]);
        $cat = Produit::find($id);
        $cat->update($request->all());
        return redirect()->route('produits.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Produit::destroy($id);
        return  redirect()->route('produits.index');
    }
    public function search(Request $request)
    {

        $param = $request->query('designation');
        $produits = Produit::where('designation', 'like', '%' . $param . '%')->get();
        return view('produits.index', compact('produits'));
    }
    // public function filter(Request $request)
    // {
    //     $minPrice = $request->input('min_price');
    //     $maxPrice = $request->input('max_price');

    //     $produits = Produit::filterByPrice($minPrice, $maxPrice)->paginate(10);

    //     return view('produits.index', compact('produits', 'minPrice', 'maxPrice'));
    // }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/produits/create.blade.php
@extends('layouts.admin')
@section('title', 'Ajouter un produit')
@section('content')
    <h1>Creer une nouvelle produit</h1>
    <form action="{{ route('produits.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="input-group-text">
            <label for="designation">Designation:</label>
            <input name="designation" class="form-control mt-0 ms-2" type="text"
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="description">Prix Unite:</label>
            <input name="prix_u" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <div class="input-group-text mt-2">
            <label for="description">Quantite Stock:</label>
            <input name="quantite_stock" class="form-control mt-0 ms-2" type="text" value=""
                aria-label="Checkbox for following text input">
        </div>

        <select class="form-select @error("categorie_id") is-invalid @enderror" name="categorie_id" id="cat_id">
            <option value="" selected>Select categorie</option>
            @foreach ($cats as $item)
                <option value="{{ $item->id }}">{{ $item->designation }}</option>
            @endforeach
        </select>
        <label for="photo">image</label>
        <input type="file" name="photo"  alt="image" >

        <div class="mt-3">
            <input type="submit" value="Ajouter">
        </div>

    </form>
    <div>
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $er)
                    <li>{{ $er }}</li>
                @endforeach
            </ul>



        @endif
    </div>
@endsection

resources/views/produits/edit.blade.php
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Produits') }}
        </h2>
    </x-slot>

    <div class="container m-auto">

        <form class="max-w-sm mx-auto mat-5" action="{{ route('produits.update', ['produit' => $data['prod']->id]) }}"
            method="POST">
            @csrf
            @method('PUT')

            <div class="mb-5">
                <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your
                    Designation</label>
                <input type="text" name="designation" value="{{ old('designation', $data['prod']->designation) }}"
                    class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">
            </div>

            <div class="mb-5">
                <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your
                    Prix Unitaire</label>
                <input type="text" name="prix_u" value="{{ old('prix_u', $data['prod']->prix_u) }}"
                    class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">
            </div>
            <div class="mb-5">
                <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                    Quantité</label>
                <input type="text" name="quantite_stock"
                    value="{{ old('quantite_stock', $data['prod']->quantite_stock) }}"
                    class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">
            </div>
            <div class="mb-5">

                <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                    Categorie</label>
                <select value="{{ old('categorie_id', $data['prod']->categorie_id) }}"
                    class="@error('categorie_id') is-invalid @enderror shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                    name="categorie_id">
                    <option value="" selected>Select categorie</option>
                    @foreach ($data['cats'] as $item)
                        <option value="{{ $item->id }}">{{ $item->designation }}</option>
                    @endforeach
                </select>
                <input type="hidden" name="photo">

            </div>
            <button type="submit"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Update
                Product
            </button>
        </form>
        <div>
            @if ($errors->any())
                <ul>
                    @foreach ($errors->all() as $er)
                        <li>{{ $er }}</li>
                    @endforeach
                </ul>
            @endif
        </div>
    </div>

</x-app-layout>

resources/views/produits/show.blade.php
@extends('layouts.admin')
@section('title','Detail d \'une categorie')
@section('content')
    <a href="{{route('produits.index')}}">Retourner vers la liste des produits</a>
    <h1>Detail de la produit Num {{$prod->id}}</h1>
    <img src="{{asset("storage/$prod->photo")}}" alt="product image">
    <div>
        <p><strong>Designation:</strong> {{$prod->designation}}</p>
        <p><strong>prix unitere:</strong> {{$prod->prix_u}}</p>
        <p><strong>quantite on stock:</strong> {{$prod->quantite_stock}}</p>
        <p><strong>id categorie:</strong> {{$prod->categorie_id}}</p>
    </div>
@endsection